[package]
name = "sphere"
version = "0.1.0"
edition = "2024"

[dependencies]
aac = { path = "../audio_decoders/aac" }
common = { path = "../common" }
etna = { path = "../etna" }
log = "0.4.34"
matroska = { path = "../demuxers/matroska" }
pretty_env_logger = "0.5.0"
sdl3 = { version = "0.18.4", features = ["build-from-source", "raw-window-handle"] }
thiserror.workspace = true
